### ISSUE TITLE
Scoreboard issue after Gun Mettle update

### ISSUE THREAD

**Issue by ValorZeroAdvent** [bw-/bw-HUD#10]
![scoreboardissue](https://cloud.githubusercontent.com/assets/13160394/8492444/7c69753e-217c-11e5-9c23-857660d55e31.png)

The score, pings and names all got squashed up after the update. What went wrong?

**Comment by bw-** [comment]
That's valve being valve. pushing a hopefully complete fix for that+.

**Comment by frshmt** [comment]
I'm still having this problem. Is there anything I can change on my end to fix it? I'm a bit new to all of this. Thanks.
