### ISSUE TITLE
itempanel in spectating and class image

### ISSUE THREAD

**Issue by MrDania** [bw-/bw-HUD#11]
Hello. I'd like to know how to reposition this box on the bottom right that tells me who I'm specting and what weapons they use. Can I reposition it slighty higher and make it smaller?

![](http://i.imgur.com/JCgEwCz.jpg)

Thanks! 
One last thing, any fixes for scoreboard columns being messed up and contracts unable to show?

**Comment by bw-** [comment]
You'll need to find itempanel in Spectator.res, and edit its wide and tall values.

scoreboard should be fixed in the latest update, but let me know if not. Working on the contracts.

**Comment by MrDania** [comment]
Thanks!
