### ISSUE TITLE
Green text on scoreboard

### ISSUE THREAD

**Issue by Bukkithead** [bw-/bw-HUD#12]
Hi,
as of the most recent update any text on the scoreboard changes from default white to this green colour (see screenshot) once the value is no longer zero. I can't see anything in the changelog (especially in ClientScheme or Scoreboard) that would obviously account for this. Is there a way to keep the numbers white as before? Thanks.

![2015-07-05_00001](https://cloud.githubusercontent.com/assets/7946901/8512631/210e4452-2344-11e5-833a-e3c64884cc8d.jpg)

**Comment by MrDania** [comment]
How are your scoreboard columns fine and your damage shows, did I do something wrong :/ ?

**Comment by Bukkithead** [comment]
If you update to the newest version it should look like this.

**Comment by MrDania** [comment]
That's the thing, I already did but it broke again after last small update. Maybe I should reinstall once again.

**Comment by bw-** [comment]
This is on valve's end. nothing i can do, sorry.
