### ISSUE TITLE
The Spectator UI is in the middle of the screen

### ISSUE THREAD

**Issue by Moppko** [bw-/bw-HUD#13]
![2015-07-06_00006](https://cloud.githubusercontent.com/assets/9677311/8532315/8f50c658-242d-11e5-8580-d52955887d7c.jpg)
If spectating while dead it will show your teams one there.

**Comment by bw-** [comment]
This is on valve, nothing i can do for now. sorry.

**Comment by Moppko** [comment]
Ok, thanks for the quick answer :+1:
