### ISSUE TITLE
Scoreboard, contracts and item notification

### ISSUE THREAD

**Issue by frshmt** [bw-/bw-HUD#14]
So I'm still having issues with my scoreboard. I installed the HUD fresh after the latest update and it still looks like this http://i.imgur.com/nlvpWs2.jpg

The contract icon is nowhere to be seen either (I have to use F2) and I just found out I get no item notification in the main menu (only the text alert in the loadouts)

Please let me know if I might be doing something wrong because it's my first time using a HUD.

Thanks.

**Comment by bw-** [comment]
Your scoreboard problems are from your resolution. unfortunately, 1366x768 is not optimal for bwhud. if you'd like to try and fix it yourself, you'll need to edit scoreboard.res and edit name_width to a smaller number.

the contract and the notification should be fixed if you properly installed. please try again and comment here.

**Comment by frshmt** [comment]
Ok, notifications are showing up. Does the contract icon only show up when there's a new contract as well? Since I don't have one currently I'm not sure if it's supposed to be there all the time or only when I get a new one.

I'm gonna give it a go messing with the scoreboard. Thanks a lot for the help.
