### ISSUE TITLE
mp_tournament_readymode 1

### ISSUE THREAD

**Issue by averagecomputerguy** [bw-/bw-HUD#15]
Please add support for mp_tournament_readymode. Here is what bwhud currently looks like with it on:
![image](https://cloud.githubusercontent.com/assets/3173124/9152359/aca1543a-3dea-11e5-82e5-20d3bbcc3b92.png)

**Comment by BillWatterson** [comment]
version 2.2.2 has fixed this.

**Comment by bw-** [comment]
version 2.2.2 has fixed this.
