### ISSUE TITLE
Extra crosshair showing up in certain classes

### ISSUE THREAD

**Issue by Decimation** [bw-/bw-HUD#16]
I found that the pilot fighter like crosshair is showing up even though I don't have any crosshairs enabled.

It's exempt for Scout though.

I don't have the default crosshairs enabled.

**Comment by bw-** [comment]
check in HudAchievementTrackerItem.res for the possibility of the secondary custom crosshair being enabled, and get back to me. thanks!

**Comment by Decimation** [comment]
That was it! Thank you. One question though, how can I move the damage counters to be on top of my health?
