### ISSUE TITLE
Missing contracts for 29/10/15 Halloween 2015 update.

### ISSUE THREAD

**Issue by ValorZeroAdvent** [bw-/bw-HUD#17]
![bwhud issue](https://cloud.githubusercontent.com/assets/13160394/10821332/dccb8b48-7e8c-11e5-8249-7bf832dd5c92.png)

There's supposed to be two contracts that occupy this area. The window has none, though.

**Comment by bw-** [comment]
should be fixed in the latest patch. let me know!

**Comment by ValorZeroAdvent** [comment]
![bwfixed](https://cloud.githubusercontent.com/assets/13160394/10837026/d49aa87e-7eef-11e5-92c5-dfb8a74e966a.png)

It's fixed. Nice work!
