### ISSUE TITLE
Disabling the uber percentage next to crosshair

### ISSUE THREAD

**Issue by Winterzduck** [bw-/bw-HUD#18]
When I set the transparency to 0 the percentage next to the crosshair still shows even after restarting my game.

("Small%"        "227 227 227 0"         //Shows Uber % under crosshair)

Is this a hud glitch or a Tf2 thing?

**Comment by bw-** [comment]
you'll need to go to resource/ui/hudmediccharge.res and find the chargelabeltiny entry. change the colour there.

**Comment by Winterzduck** [comment]
cool thank you
