### ISSUE TITLE
Vaccinator

### ISSUE THREAD

**Issue by HeyItsNix** [bw-/bw-HUD#8]
I love this hud! It's super cool, and as a general rule I like its styling, but the vaccinator hud element just seems broken. My screen shows two overlayed percentages, in different colors (like an offset shadow) and the bar itself looks odd. If this is an issue with my hud, I'd love to know where I could fix it from.
Thanks!
(example image attached)
![2014-12-22_00001](https://cloud.githubusercontent.com/assets/8406326/5531220/104f2be0-89de-11e4-9dd6-04739a1f86a9.jpg)

**Comment by bw-** [comment]
fixed in 2.1.8
