### ISSUE TITLE
Engineer Metal Count 

### ISSUE THREAD

**Issue by Inferno989** [bw-/bw-HUD#9]
I have really been enjoying the HUD as a whole, however i came across an issue which i'm not sure if it's just like that or if it's an actual mistake or if i'm going mad. So I usually play engie a lot and every time I put my crosshair on a building "mainly the tele and dispenser" the metal count in the middle overlayed the amount for the upgrade process.
http://gyazo.com/b4fbfd5c4d46b41d2e9c4d245c406c84
http://gyazo.com/1de3ddedacbedc5485677a80adf28079

Visually for me it's a bit irritating but obviously not a big issue. However if it is because of the HUD it would be nice if the metal count's position was moved up slightly.

**Comment by bw-** [comment]
fixed in 2.1.8
